In [1]:
import numpy as np
import sympy as sp

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 0], [-1, 2]])
x = np.array([3, -1])

print("A + B =\n", A + B)
print("3A =\n", 3*A)
print("A^T =\n", A.T)
print("AB =\n", A @ B)
print("BA =\n", B @ A)
print("Ax =", A @ x)

A + B =
 [[6 2]
 [2 6]]
3A =
 [[ 3  6]
 [ 9 12]]
A^T =
 [[1 3]
 [2 4]]
AB =
 [[ 3  4]
 [11  8]]
BA =
 [[ 5 10]
 [ 5  6]]
Ax = [1 5]


In [2]:
A = sp.Matrix([[1, -1, -1],
               [3, -1,  2],
               [2,  2,  3]])

print("det A =", A.det())
Ainv = A.inv()
display(Ainv)
display(A * Ainv)

det A = -10


Matrix([
[7/10, -1/10, 3/10],
[ 1/2,  -1/2,  1/2],
[-4/5,   2/5, -1/5]])

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])