# Matrizes

Uma **matriz** é uma tabela retangular de números, organizada em linhas e colunas. Uma matriz com $m$ linhas e $n$ colunas é dita de tamanho $m\times n$:

$$
A = \begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{21} & a_{22} & \cdots & a_{2n}\\
\vdots & \vdots & & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{pmatrix}.
$$

O número $a_{ij}$ é o **elemento** na linha $i$ e coluna $j$ (primeiro a linha, depois a coluna). Dois casos especiais nos interessam:

* **matrizes quadradas** ($m=n$), como os coeficientes de um sistema $\mathbf{x}'=A\mathbf{x}$;
* **vetores** (coluna), que são matrizes $n\times1$, como o vetor de incógnitas $\mathbf{x}$.

Por exemplo,

$$
A = \begin{pmatrix} 1 & -2 & 0\\ 3 & 4 & 5\end{pmatrix}\ (2\times3), \qquad
B = \begin{pmatrix} 2 & 1\\ 0 & -1\end{pmatrix}\ (2\times2), \qquad
\mathbf{x} = \begin{pmatrix} 3\\ -1\end{pmatrix}\ (2\times1).
$$

Em $A$, temos $a_{12}=-2$ e $a_{23}=5$.

## Operações básicas

**Soma.** Matrizes de mesmo tamanho são somadas elemento a elemento:

$$
\begin{pmatrix} 1 & 2\\ 3 & 4\end{pmatrix} + \begin{pmatrix} 5 & 0\\ -1 & 2\end{pmatrix} = \begin{pmatrix} 6 & 2\\ 2 & 6\end{pmatrix}.
$$

**Multiplicação por um número.** Cada elemento é multiplicado:

$$
3\begin{pmatrix} 1 & 2\\ 3 & 4\end{pmatrix} = \begin{pmatrix} 3 & 6\\ 9 & 12\end{pmatrix}.
$$

**Transposta.** A transposta $A^T$ troca linhas por colunas ($a_{ij}$ vai para a posição $ji$):

$$
\begin{pmatrix} 1 & -2 & 0\\ 3 & 4 & 5\end{pmatrix}^T = \begin{pmatrix} 1 & 3\\ -2 & 4\\ 0 & 5\end{pmatrix}.
$$

Em particular, a transposta de um vetor coluna é um vetor linha. Uma matriz quadrada com $A^T=A$ é chamada **simétrica**.

**Matriz nula e matriz identidade.** A matriz nula $0$ tem todos os elementos iguais a zero. A **identidade** $I$ é a matriz quadrada com $1$ na diagonal e $0$ fora dela:

$$
I = \begin{pmatrix} 1 & 0\\ 0 & 1\end{pmatrix} \quad (2\times2), \qquad
I = \begin{pmatrix} 1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 1\end{pmatrix} \quad (3\times3).
$$

## Multiplicação de matrizes

Esta é a operação mais importante, e a menos intuitiva. O produto $AB$ só está definido se o **número de colunas de $A$** for igual ao **número de linhas de $B$**: se $A$ é $m\times n$ e $B$ é $n\times r$, então $AB$ é $m\times r$.

O elemento na linha $i$ e coluna $j$ de $AB$ é obtido multiplicando a **linha $i$ de $A$** pela **coluna $j$ de $B$**, termo a termo, e somando:

$$
(AB)_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + \cdots + a_{in}b_{nj}.
$$

**Exemplo.**

$$
\begin{pmatrix} 1 & 2\\ 3 & 4\end{pmatrix}\begin{pmatrix} 5 & 0\\ -1 & 2\end{pmatrix}
= \begin{pmatrix} 1\cdot5+2\cdot(-1) & 1\cdot0+2\cdot2\\ 3\cdot5+4\cdot(-1) & 3\cdot0+4\cdot2\end{pmatrix}
= \begin{pmatrix} 3 & 4\\ 11 & 8\end{pmatrix}.
$$

**Cuidado: a multiplicação não é comutativa.** Em geral, $AB\neq BA$. Trocando a ordem no exemplo acima:

$$
\begin{pmatrix} 5 & 0\\ -1 & 2\end{pmatrix}\begin{pmatrix} 1 & 2\\ 3 & 4\end{pmatrix} = \begin{pmatrix} 5 & 10\\ 5 & 6\end{pmatrix} \neq \begin{pmatrix} 3 & 4\\ 11 & 8\end{pmatrix}.
$$

A multiplicação é, porém, associativa, $(AB)C=A(BC)$, e distributiva, $A(B+C)=AB+AC$. E a identidade se comporta como o número $1$: $AI=IA=A$.

### Matriz vezes vetor

O caso que mais vamos usar é o produto de uma matriz $n\times n$ por um vetor $n\times1$, que dá outro vetor $n\times1$:

$$
\begin{pmatrix} a & b\\ c & d\end{pmatrix}\begin{pmatrix} x_1\\ x_2\end{pmatrix} = \begin{pmatrix} ax_1+bx_2\\ cx_1+dx_2\end{pmatrix}.
$$

É exatamente o que permite escrever um sistema de equações lineares de forma compacta: o sistema

$$
\begin{aligned}
2x_1 - x_2 &= 1\\
x_1 + 3x_2 &= 4
\end{aligned}
\qquad\text{é o mesmo que}\qquad
\begin{pmatrix} 2 & -1\\ 1 & 3\end{pmatrix}\begin{pmatrix} x_1\\ x_2\end{pmatrix} = \begin{pmatrix} 1\\ 4\end{pmatrix},
$$

ou seja, $A\mathbf{x}=\mathbf{b}$. Foi o mesmo truque que usamos na aula passada para escrever $\mathbf{x}'=A\mathbf{x}$.

No Python, o `numpy` faz essas contas (o produto de matrizes é o operador `@`), e o `sympy` faz as mesmas contas de forma exata:

In [1]:
import numpy as np
import sympy as sp

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 0], [-1, 2]])
x = np.array([3, -1])

print("A + B =\n", A + B)
print("3A =\n", 3*A)
print("A^T =\n", A.T)
print("AB =\n", A @ B)
print("BA =\n", B @ A)
print("Ax =", A @ x)

A + B =
 [[6 2]
 [2 6]]
3A =
 [[ 3  6]
 [ 9 12]]
A^T =
 [[1 3]
 [2 4]]
AB =
 [[ 3  4]
 [11  8]]
BA =
 [[ 5 10]
 [ 5  6]]
Ax = [1 5]


Repare que `A * B` (com asterisco) **não** é o produto de matrizes no `numpy`: ele multiplica elemento a elemento, o que quase nunca é o que queremos. Para o produto de matrizes, use sempre `@`.

## Determinante

A cada matriz **quadrada** associamos um número, o **determinante**, que vai responder a uma pergunta central: *o sistema $A\mathbf{x}=\mathbf{b}$ tem solução única?*

**Matriz $2\times2$:**

$$
\det\begin{pmatrix} a & b\\ c & d\end{pmatrix} = \begin{vmatrix} a & b\\ c & d\end{vmatrix} = ad - bc.
$$

**Matriz $3\times3$:** expandimos pela primeira linha, alternando sinais, e cada elemento multiplica o determinante $2\times2$ que sobra ao apagar sua linha e sua coluna:

$$
\begin{vmatrix} a_{11} & a_{12} & a_{13}\\ a_{21} & a_{22} & a_{23}\\ a_{31} & a_{32} & a_{33}\end{vmatrix}
= a_{11}\begin{vmatrix} a_{22} & a_{23}\\ a_{32} & a_{33}\end{vmatrix}
- a_{12}\begin{vmatrix} a_{21} & a_{23}\\ a_{31} & a_{33}\end{vmatrix}
+ a_{13}\begin{vmatrix} a_{21} & a_{22}\\ a_{31} & a_{32}\end{vmatrix}.
$$

(Você talvez conheça a "regra de Sarrus" do ensino médio, que dá o mesmo resultado para $3\times3$.)

**Exemplo.**

$$
\begin{vmatrix} 1 & -1 & -1\\ 3 & -1 & 2\\ 2 & 2 & 3\end{vmatrix}
= 1\begin{vmatrix} -1 & 2\\ 2 & 3\end{vmatrix} - (-1)\begin{vmatrix} 3 & 2\\ 2 & 3\end{vmatrix} + (-1)\begin{vmatrix} 3 & -1\\ 2 & 2\end{vmatrix}
= 1(-7) + 1(5) - 1(8) = -10.
$$

O fato mais importante sobre o determinante, que vamos usar o tempo todo:

> Uma matriz quadrada $A$ é **invertível** se, e somente se, $\det A\neq0$.

Uma matriz com $\det A=0$ é chamada **singular**.

## Inversa

Acabamos de ver que quando uma matriz tem determinante diferente de zero, ela é invertível. Isso implica que existe uma matriz $A^{-1}$ tal que

$$
AA^{-1} = A^{-1}A = I.
$$

A matriz $A^{-1}$ é chamada de **inversa** da matriz $A$. Ela faz o papel de "dividir por $A$": se $A\mathbf{x}=\mathbf{b}$ e $A$ é invertível, multiplicando os dois lados por $A^{-1}$ obtemos $\mathbf{x}=A^{-1}\mathbf{b}$.

**Fórmula para $2\times2$.** Se $\det(A)=ad-bc\neq0$,

$$
\begin{pmatrix} a & b\\ c & d\end{pmatrix}^{-1} = \frac{1}{ad-bc}\begin{pmatrix} d & -b\\ -c & a\end{pmatrix}
$$

(troca os elementos da diagonal, troca o sinal dos outros dois, divide pelo determinante). Por exemplo,

$$
\begin{pmatrix} 2 & -1\\ 1 & 3\end{pmatrix}^{-1} = \frac17\begin{pmatrix} 3 & 1\\ -1 & 2\end{pmatrix}.
$$

### Inversa pelo método de Gauss–Jordan

Para matrizes maiores, o método prático é o de **eliminação de Gauss–Jordan**. Usamos três **operações elementares** sobre as linhas:

1. trocar duas linhas de lugar;
2. multiplicar uma linha por um número diferente de zero;
3. somar a uma linha um múltiplo de outra linha.

Escrevemos a **matriz aumentada** $(A\,|\,I)$ e aplicamos operações elementares até transformar o lado esquerdo em $I$. O lado direito, ao final, será $A^{-1}$.

**Exemplo.** Encontre a inversa de $A = \begin{pmatrix} 1 & -1 & -1\\ 3 & -1 & 2\\ 2 & 2 & 3\end{pmatrix}$.

Começamos com a matriz aumentada:

$$
\left(\begin{array}{ccc|ccc} 1 & -1 & -1 & 1 & 0 & 0\\ 3 & -1 & 2 & 0 & 1 & 0\\ 2 & 2 & 3 & 0 & 0 & 1\end{array}\right).
$$

*(a)* Zeramos a primeira coluna abaixo da diagonal: $L_2\leftarrow L_2-3L_1$ e $L_3\leftarrow L_3-2L_1$:

$$
\left(\begin{array}{ccc|ccc} 1 & -1 & -1 & 1 & 0 & 0\\ 0 & 2 & 5 & -3 & 1 & 0\\ 0 & 4 & 5 & -2 & 0 & 1\end{array}\right).
$$

*(b)* Fazemos $1$ na diagonal da segunda coluna: $L_2\leftarrow \tfrac12L_2$:

$$
\left(\begin{array}{ccc|ccc} 1 & -1 & -1 & 1 & 0 & 0\\ 0 & 1 & \tfrac52 & -\tfrac32 & \tfrac12 & 0\\ 0 & 4 & 5 & -2 & 0 & 1\end{array}\right).
$$

*(c)* Zeramos o resto da segunda coluna: $L_1\leftarrow L_1+L_2$ e $L_3\leftarrow L_3-4L_2$:

$$
\left(\begin{array}{ccc|ccc} 1 & 0 & \tfrac32 & -\tfrac12 & \tfrac12 & 0\\ 0 & 1 & \tfrac52 & -\tfrac32 & \tfrac12 & 0\\ 0 & 0 & -5 & 4 & -2 & 1\end{array}\right).
$$

*(d)* Fazemos $1$ na diagonal da terceira coluna: $L_3\leftarrow -\tfrac15L_3$:

$$
\left(\begin{array}{ccc|ccc} 1 & 0 & \tfrac32 & -\tfrac12 & \tfrac12 & 0\\ 0 & 1 & \tfrac52 & -\tfrac32 & \tfrac12 & 0\\ 0 & 0 & 1 & -\tfrac45 & \tfrac25 & -\tfrac15\end{array}\right).
$$

*(e)* Zeramos o resto da terceira coluna: $L_1\leftarrow L_1-\tfrac32L_3$ e $L_2\leftarrow L_2-\tfrac52L_3$:

$$
\left(\begin{array}{ccc|ccc} 1 & 0 & 0 & \tfrac{7}{10} & -\tfrac{1}{10} & \tfrac{3}{10}\\ 0 & 1 & 0 & \tfrac12 & -\tfrac12 & \tfrac12\\ 0 & 0 & 1 & -\tfrac45 & \tfrac25 & -\tfrac15\end{array}\right)
\quad\Longrightarrow\quad
A^{-1} = \begin{pmatrix} \tfrac{7}{10} & -\tfrac{1}{10} & \tfrac{3}{10}\\ \tfrac12 & -\tfrac12 & \tfrac12\\ -\tfrac45 & \tfrac25 & -\tfrac15\end{pmatrix}.
$$

Se em algum momento aparecer uma linha inteira de zeros no lado esquerdo, a matriz não tem inversa (é singular). Vamos conferir com o computador, inclusive que $AA^{-1}=I$:

In [2]:
A = sp.Matrix([[1, -1, -1],
               [3, -1,  2],
               [2,  2,  3]])

print("det A =", A.det())
Ainv = A.inv()
display(Ainv)
display(A * Ainv)

det A = -10


Matrix([
[7/10, -1/10, 3/10],
[ 1/2,  -1/2,  1/2],
[-4/5,   2/5, -1/5]])

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## Funções matriciais

Nos sistemas de EDOs, os vetores têm elementos que são **funções** de $t$:

$$
\mathbf{x}(t) = \begin{pmatrix} x_1(t)\\ x_2(t)\end{pmatrix}.
$$

Derivar (ou integrar) um vetor ou uma matriz é fazer isso **elemento a elemento**:

$$
\mathbf{x}(t) = \begin{pmatrix} e^{2t}\\ \text{sen}\,t\end{pmatrix}
\quad\Longrightarrow\quad
\mathbf{x}'(t) = \begin{pmatrix} 2e^{2t}\\ \cos t\end{pmatrix}.
$$

Com isso, já podemos verificar se uma função vetorial é solução de um sistema, exatamente como fazíamos com uma equação só: derivar e substituir. Por exemplo, vamos verificar que

$$
\mathbf{x}(t) = \begin{pmatrix} 1\\ 1\end{pmatrix}e^{2t} = \begin{pmatrix} e^{2t}\\ e^{2t}\end{pmatrix}
\qquad\text{é solução de}\qquad
\mathbf{x}' = \begin{pmatrix} 3 & -1\\ 4 & -2\end{pmatrix}\mathbf{x}.
$$

De um lado, $\mathbf{x}' = \begin{pmatrix} 2e^{2t}\\ 2e^{2t}\end{pmatrix}$. Do outro,

$$
\begin{pmatrix} 3 & -1\\ 4 & -2\end{pmatrix}\begin{pmatrix} e^{2t}\\ e^{2t}\end{pmatrix} = \begin{pmatrix} 3e^{2t}-e^{2t}\\ 4e^{2t}-2e^{2t}\end{pmatrix} = \begin{pmatrix} 2e^{2t}\\ 2e^{2t}\end{pmatrix}. \quad\checkmark
$$

Guarde esse exemplo: a solução tem a forma "vetor constante vezes exponencial", e isso não é coincidência. É o ponto de partida do método que vamos desenvolver para resolver $\mathbf{x}'=A\mathbf{x}$.